"""step validation requests

Revision ID: 0a2dbf49c3b6
Revises: 0e8bd1137993
Create Date: 2026-05-26 10:58:17.934773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a2dbf49c3b6'
down_revision = '0e8bd1137993'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roadmap_step_log', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'step_validation_request', ['validation_request_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roadmap_step_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
