"""Kangaroo extended schema

Revision ID: 0e8bd1137993
Revises: 
Create Date: 2026-05-25 11:19:49.594603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e8bd1137993'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.alter_column('startup_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('startup', schema=None) as batch_op:
        batch_op.alter_column('roadmap_step',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('team_member', schema=None) as batch_op:
        batch_op.alter_column('team_role',
               existing_type=sa.VARCHAR(length=40),
               nullable=False,
               existing_server_default=sa.text("'member'"))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('onboarding_done',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('account_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'user'"))
        batch_op.alter_column('locale',
               existing_type=sa.VARCHAR(length=5),
               nullable=False,
               existing_server_default=sa.text("'ru'"))
        batch_op.alter_column('ai_requests_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('is_verified_investor',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('open_for_messages',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('is_premium',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.create_foreign_key('fk_user_active_startup', 'startup', ['active_startup_id'], ['id'], use_alter=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_active_startup', type_='foreignkey')
        batch_op.alter_column('is_premium',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('open_for_messages',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('is_verified_investor',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('ai_requests_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('locale',
               existing_type=sa.VARCHAR(length=5),
               nullable=True,
               existing_server_default=sa.text("'ru'"))
        batch_op.alter_column('account_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'user'"))
        batch_op.alter_column('onboarding_done',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('team_member', schema=None) as batch_op:
        batch_op.alter_column('team_role',
               existing_type=sa.VARCHAR(length=40),
               nullable=True,
               existing_server_default=sa.text("'member'"))

    with op.batch_alter_table('startup', schema=None) as batch_op:
        batch_op.alter_column('roadmap_step',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.alter_column('startup_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
